pipeline:
  name: demopipeline-2403
  identifier: demopipeline2403
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubharness2103
        repoName: jacoco-example-project
        build: <+input>
  stages:
    - stage:
        name: build-2403
        identifier: build2403
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Build
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: mvn clean install
              - step:
                  type: Test
                  name: Test_1
                  identifier: Test_1
                  spec:
                    shell: Sh
                    command: mvn test
                    intelligenceMode: true
              - step:
                  type: Sonarqube
                  name: Sonarqube_1
                  identifier: Sonarqube_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
                    auth:
                      access_token: sqp_56ba788a811c7a5f067729a62f8a2c943ab89a8b
                      domain: http://34.132.216.193:9000/
                      ssl: false
                    tool:
                      java:
                        binaries: target/classes
                      project_key: Jaco
              - step:
                  type: ArtifactoryUpload
                  name: ArtifactoryUpload_1
                  identifier: ArtifactoryUpload_1
                  spec:
                    connectorRef: jfrogconnector
                    target: demoharness-libs-snapshot
                    sourcePath: /root/.m2/repository/
          sharedPaths:
            - /root/.m2/repository/
          caching:
            enabled: false
            paths: []
          buildIntelligence:
            enabled: false
